salaryapp/posts/forms.py
# POSTS FORMS
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = StringField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

salaryapp/core/views.py
# CORE / VIEWS.PY

from flask import render_template, request, Blueprint
from salaryapp.models import Post

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page, per_page=6)
    return render_template('index.html', posts=posts)

@core.route('/about')
def about():
    return render_template('about.html')

salaryapp/posts/views.py
# POSTS/VIEWS.PY
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from siteapp import db
from salaryapp.models import Post
from salaryapp.posts.forms import PostForm

posts = Blueprint('posts', __name__)

# CREATE A POST
@posts.route('/create', methods=['GET','POST'])
@login_required
def create_post():
    form = PostForm()

    if form.validate_on_submit():

        post = Post(title=form.title.data, text=form.text.data, user_id=current_user.id)

        db.session.add(post)
        db.session.commit()
        flash('Post created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)

# VIEW A POST
@posts.route('/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, date=post.date, text=post.text, post=post)

# UPDATE A POST
@posts.route("/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('posts.post', post_id=post.id))
    # Pass back the old post information so they can start again with the old text and title.
    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text
    return render_template('create_post.html', title='Update', form=form)

# DELETE A POST
@posts.route('/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted')
    return redirect(url_for('core.index'))

salaryapp/users/views.py
# USERS/VIEWS.PY
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from salaryapp import db
from salaryapp.models import User, Post
from salaryapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from salaryapp.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

# register users
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Login success')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html', form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

# account (update UpdateUserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


# user's list of Posts
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

salaryapp/templates/about.html
{% extends "base.html" %}

{% block content %}

<p class="lead"><strong>Deep Tech with purpose</strong></p>

<div class="container">

  <p>Artificial Intelligence, Deep Learning, Blockchain, Big Data&hellip; The world of digital technology is boiling. Numbers of startups are booming everywhere, and all industries have started their &ldquo;Digital Transformation&rdquo; journey. We are not talking any more of change, but of &ldquo;disruption&rdquo;. Huge companies know that if they don&rsquo;t adapt quickly, they could see their business model collapse almost overnight.</p>
  <p>In this personal homepage I am exploring the wonderland of Deep Tech. I am focusing in particular on Web applications, Data analytics, Visualization, Machine Learning, Deep Learning, and Blockchain.</p>
  <a class="btn btn-primary btn-sm" href="#" role="button">Read more</a>

</div>

{% endblock %}

salaryapp/templates/account.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <div align="center">
    <h1>Welcome to the page for {{ current_user.username }}</h1>
    <img align="center" height="40" src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}">
</div>

<div class="container">
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.username.label }} {{ form.username(class="form-control") }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.email.label }} {{ form.email(class="form-control") }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.picture.label }} {{ form.picture() }}
      </div>
    </div>

    <br>
    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>


{% endblock %}

salaryapp/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>

    <meta charset="utf-8">
    <title>Flask App Project: Salary prediction model</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style type="text/css">

  	#navbar {
  		padding-left:40px;
  		padding-right:40px;
  		background-color:#F5F5FF;
  		border-bottom: 1px solid #BCBCBC;
  	}

  	#jumbo1 {
  		font-family: 'Crimson Text', serif !important;
  		margin-top:70px;
  		margin-left:40px;
  		margin-right:40px;
  		padding-top:20px;
  		padding-right:20px;
  		background-color:#1E0180;
  		box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  	}

  	#jumbo2 {
  		margin-top:12px;
  		margin-left:40px;
  		margin-right:40px;
  		padding:20px;
  		background-color:#EEE;
  	}

  	#cardDeck {
  		margin-top:-25px;
  		margin-left:40px;
  		margin-right:40px;
  		padding:20px;
  		background-color:#EEE;
  	}

  	.card {
  		box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  	}

  	</style>

  </head>

  <body>

    <div class="container">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light" id="navbar">
  	  <a class="navbar-brand" href="{{url_for('core.index')}}">FLASK APP PROJECT</a>
  	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
  		<span class="navbar-toggler-icon"></span>
  	  </button>
  	  <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
    		<div class="navbar-nav">
          <a class="nav-item nav-link" href="{{url_for('core.about')}}">About</a>

          {% if current_user.is_authenticated %}

          <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
          <a class="nav-item nav-link" href="{{ url_for('users.account')}}">Account</a>
          <a class="nav-item nav-link" href="{{ url_for('posts.create_post')}}">Create Post</a>

          {% else %}

          <a class="nav-item nav-link" href="{{ url_for('users.login')}}">login</a>
          <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>

          {% endif %}

    		</div>
  	  </div>
  	</nav>
  </div>

  <div class="jumbotron-fluid" id="jumbo1">
    <div class="row d-flex flex-wrap align-items-center">
      <div class="col-md-11">
        <h1 class="text-white font-italic text-center" id="quote">"The ultimate goal is to have the freedom to do what we want."</h1>
        <p class="text-white font-italic text-center" id="quote-author">Hans Rosling</p>
      </div>
<!--      <div class="col-md-1">
        <img class="float-right" id="arrow" src="images/white-arrow.png">
      </div>
-->    </div>
  </div>

  <div class="jumbotron" id="jumbo2">
          {% block content %}
          {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  </body>

</html>

salaryapp/templates/create_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <form class="form-group" method="POST">
      {{form.hidden_tag()}}

      <div class="form-group">
        {{form.title.label(class="form-control-label")}}
        {{form.title(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.text.label(class="form-control-label")}}
        {{form.text(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>

    </form>
  </div>
{% endblock %}

salaryapp/templates/index.html
{% extends "base.html" %}

{% block content %}

  <div class="container">

    {% for post in posts.items %}
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">

          <h4><a class="card-title" href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a></h2>
          <a href="{{url_for('users.user_posts', username=post.author.username)}}">Written by: {{ post.author.username }}</a>
          <p>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
          <a class="btn btn-primary" href="{{url_for('posts.post', post_id=post.id)}}">Read post</a>

        </div>
      </div>
    </div>
  {% endfor %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
       {% if posts.page == page_num %}
       <li class="page-item disabled">
         <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
       </li>
       {% else %}
         <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
       {% endif %}
   {% endfor %}
 </nav>

{% endblock %}

salaryapp/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <form method="POST">
    {{ form.hidden_tag() }}

    <div class="">
      <h2>Login</h2><br>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.email.label(class="form-group") }} {{ form.email(class="form-control") }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.password.label(class="form-group") }} {{ form.password(class="form-control") }}
      </div>
    </div>
    <br>
    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>

{% endblock %}

salaryapp/templates/post.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h1>{{ title }}</h1>
    <h2>Written by: {{ post.author.username }}</h2>
    <h3>Published: {{ date.strftime('%B-%d-%Y') }}</h3>
    <p>{{ text }}</p>
  </div>

  {% if post.author == current_user %}
    <div>
      <a class="btn btn-secondary" href="{{ url_for('posts.update', post_id=post.id) }}">Update</a>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
    </div>
  {% endif %}

  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

salaryapp/templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <form method="POST">
    {{ form.hidden_tag() }}

    <div class="">
      <h2>Registration form</h2><br>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.email.label }} {{ form.email(class="form-control") }}
        {{ form.username.label }} {{ form.username(class="form-control") }}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-4">
        {{ form.password.label }} {{ form.password(class="form-control") }}
        {{ form.pass_confirm.label }} {{ form.pass_confirm(class="form-control") }}
      </div>
    </div>
    <br>
    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>

{% endblock %}

salaryapp/templates/user_posts.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <div align="center">
    <h1>Welcome to the page for {{ user.username }}</h1>
    <img src="{{ url_for('static', filename='profile_pics/'+user.profile_image)}}">
  </div>

  {% for post in posts.items %}

    <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
    Written by: {{ post.author.username }}</a>
    <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
    <br>
    <p>{{ post.text }}</p>
    <br>

    {% endfor %}

  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
         {% if posts.page == page_num %}
         <li class="page-item disabled">
           <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
         </li>
         {% else %}
           <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
         {% endif %}
     {% endfor %}
   </nav>

{% endblock %}